workflows:
  ia-bets:
    name: IABets
    max_build_duration: 120
    environment:
      vars:
        APP_STORE_CONNECT_PRIVATE_KEY: |-
          -----BEGIN PRIVATE KEY-----
          MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgU+bbxSfMGtUq/Lys
          2MLMHMh8d8qdh0hMobT4QsHGH06gCgYIKoZIzj0DAQehRANCAARcc1tIz69Us3D6
          ph/g3rKAnu3K2OOp9msnzRUJPSeYymCwsxVw5BtboSRp0PWCnnzhCGY1TX1EZLFk
          bZ2pSqqB
          -----END PRIVATE KEY-----
        CERTIFICATE_PRIVATE_KEY: |-
          -----BEGIN RSA PRIVATE KEY-----
          fjr8EOGhqRtNSlxkq6UBpwbRsp38Hxs1e7bVO6clvN3+JCnaFsT3ZqIwIOcAblxX
          t2zw686XX2VWGeJBeAsaZO4/hkgdOBb31HPHvH6abxts5YjyPPsIZQLDw55UIPok
          P3eAEjsCQNBb1wEKxsbFMCSOetpN77cyYq6xNySAUMY1CdKDqBD5hhAFpIFZO7OM
          fCxJXfKcO3jcGzWtfvIx7CdYHNVD7p+KR40YHFRrfUiDXasmQNo5sQkdTCaEKqOs
          IEGKxphphFAIuqTkQZFa2ozBRAj+I7/8oVc8tUyM4XVOaT2UrI2fPuR3kr2XRUeM
          /xwwQbEy1DaJ8SrINWRgiWVVrSBmz39DYc6yyc0u6gbl6OTSmId+oB5e2Fosd6ZW
          UPGHbAcWc6A6fjzpiYIPQGbryliDlfx8tj4nomY6xOEqqcbcTr+fLy9tPEeMdAzQ
          /fFOoU3FC7cK2WFw1IA5OTffIuqby2h/0tuGVwJWEICG1Ufv9AKRKS+uz9WcQ23o
          VJy300HQSZeAsokKVHbEItDWKT2Byu+U3pLExQRPDkdgURafRA2nAYhEpZ/is/+X
          eCX1lzrOJUcY0Sd//5zscckrkgfBY53u6OkCXfcwhaD5xej5xvqqlBA12p1pMh2V
          cxjUdOpK8KSA6Y0HJnVp4L+dmpcVsSWgRL7DUvjKbbcr6mpb07dZGsBk6HCd6e2p
          V6P1uF33nqzYtJGxFwlQrfmEEzWY+PS+lOXEbT3N0k2D6bayVwxS3FidHNttZbRU
          Gl7qUDDNpodJXtkoPPqK7IZUhpkm2db3fjnAWZsN/G3ELRcqw/6LdSl/v9GapjnC
          FeccI0HgWPxjLCE507qXV709b9nhTsv5+CPwCC8UJnEraon6u8ZND6MYu5bn5sLr
          /TEMAWnjpz2j0YvgkOPX6batZjt0TXGY7CL0zhrEIQe1++gJBBRCCXbWmeYfz3a9
          rrSRBXQ0lsZ4yqLfAk/TN7QE2rju7Q/1vEWUr4CjL9SmUKIifXUyAnp54VjgTfRE
          wKmCDn34HeUOQZT1ZGgHOV08wSxPw22+AbEtPBm0xBj9BBb1Sw0LgEjEbfu3g4c9
          6YYc33XxQtICvBe79KzNdBlT4a3CqGIv8tszZ9fDh2h8dJxKXT5TfoW6J2QH7aFA
          lAlMnOHzoPpmwRSqBPjXM/Xg0IulyiABKggbnKPAh4AqaNWI5ET0RPO49mrlyAWM
          eu4pbCs89VtxN3PlEMVMp4wR4TsUVuRvdKldvAvUgdnyDg0h5apm+BQRGlAICNqO
          azJeTqds/vbjARgF/2KFguFLge254r0kUhmD1H409gWDwpqlF/yQQ0zc78obJWub
          Blic75ka3FhvfxpuQzxdVK3LvpJHD7EKJ5OYuyGAMSfzQ7rS+5+qbXBSGgU3ptOQ
          5filZn3PsUymPF1ygUvfbGRsWpfdeYdvxfBkf4QYXp3YJEtkQXpmgBR73IvK1yC4
          lLcwULtzfyVG7K3IHJcP3V8gli7biYttaYIBBiXZtKZfYI9s5D1C0uc6pm47qF8S
          KMRh+MCvOMo+jVzUQ5ZWGj1FLwhpS5LtOYYXY1e7bIL6WOYVoS6Brg==
          -----END RSA PRIVATE KEY-----
        APP_STORE_CONNECT_ISSUER_ID: 2e2875a6-4622-4c8d-af2c-288e1db44239
        APP_STORE_CONNECT_KEY_IDENTIFIER: Z2UZZ867U7
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"                
        BUNDLE_ID: "br.com.iabetsoficial" # <-- Put your bundle id here
        APP_STORE_ID: 1612458696 # <-- Use the TestFlight Apple id number (An automatically generated ID assigned to your app) found under General > App Information > Apple ID. 
      flutter: stable
    scripts:
      - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
        script: |
          keychain initialize
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files $BUNDLE_ID --type IOS_APP_STORE --create
      - name: Use system default keychain
        script: |
          keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          cd . && flutter packages pub get
      #- name: Flutter analyze
      #  script: |
      #    cd . && flutter analyze
      #- name: Flutter unit tests
      #  script: |
      #    cd . && flutter test
      #  ignore_failure: true          
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter build ipa and automatic versioning
        script: |
          flutter build ipa --release \
          --build-name=1.0.0 \
          --build-number=$(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_ID") + 1)) \
          --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      # See the following link for details about email publishing - https://docs.codemagic.io/yaml-publishing/email
      email:
        recipients:
          - marcosgomesneto@gmail.com
        notify:
          success: true # To receive a notification when a build succeeds
          failure: true # To not receive a notification when a build fails
      slack:
        # See the following link about how to connect your Slack account - https://docs.codemagic.io/yaml-publishing/slack
        channel: '#builds'
        notify_on_build_start: true # To receive a notification when a build starts
        notify:
          success: true # To receive a notification when a build succeeds
          failure: false # To not receive a notification when a build fails
      app_store_connect:   # https://docs.codemagic.io/publishing-yaml/distribution              
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER  # Alphanumeric value that identifies the API key, can also reference environment variable such as $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID # Alphanumeric value that identifies who created the API key, can also reference environment variable such as $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: false     