workflows:
  ia-bets:
    name: IABets
    max_build_duration: 120
    environment:
      vars:
        APP_STORE_CONNECT_PRIVATE_KEY: |-
          -----BEGIN PRIVATE KEY-----
          MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgU+bbxSfMGtUq/Lys
          2MLMHMh8d8qdh0hMobT4QsHGH06gCgYIKoZIzj0DAQehRANCAARcc1tIz69Us3D6
          ph/g3rKAnu3K2OOp9msnzRUJPSeYymCwsxVw5BtboSRp0PWCnnzhCGY1TX1EZLFk
          bZ2pSqqB
          -----END PRIVATE KEY-----
        CERTIFICATE_PRIVATE_KEY: |-
          -----BEGIN CERTIFICATE-----
          MIIFvzCCBKegAwIBAgIQE4hZxk280SyrhTw4Ka3jCjANBgkqhkiG9w0BAQsFADB1
          MUQwQgYDVQQDDDtBcHBsZSBXb3JsZHdpZGUgRGV2ZWxvcGVyIFJlbGF0aW9ucyBD
          ZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTELMAkGA1UECwwCRzMxEzARBgNVBAoMCkFw
          cGxlIEluYy4xCzAJBgNVBAYTAlVTMB4XDTIyMDMwNDAyMzUzMFoXDTIzMDMwNDAy
          MzUyOVowgZoxGjAYBgoJkiaJk/IsZAEBDAo5WTNQNENWM0ZKMT0wOwYDVQQDDDRp
          UGhvbmUgRGlzdHJpYnV0aW9uOiBHdWlsaGVybWUgUXVlaXJvZ2EgKDlZM1A0Q1Yz
          RkopMRMwEQYDVQQLDAo5WTNQNENWM0ZKMRswGQYDVQQKDBJHdWlsaGVybWUgUXVl
          aXJvZ2ExCzAJBgNVBAYTAlVTMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKC
          AQEApWnM2UtHRKE9e/KjE5cnkznZiL8Op46dIaKJ9yuBPDr5cCx19dhjKN5387K3
          CWjNA+6P8cZYssj7uvziS8gdKn0cXYsQNtV2OMwr5c7d7g/0duPwG9P/fMLmxjEC
          Qcb5fuIG0J4jvRmqCU5UmeF4XNGDG1zg+DFhR6rz31YxVg7UM4gflVRwRZYVzEZl
          MOkH+0nACO+hUxATUOXIBFe3BanSS4fDGBh5/EoSvDl1v17ikZhDx2AlbMl/U7Zl
          W3PFyti0AS19Wte4kJz2rBGVv7PTPvrAitdY/cDSPN5a0tEqpZa5Wk7p1YQOM3Sr
          SaSisMI4PcOBcpPD+/u9QR28VwIDAQABo4ICIzCCAh8wDAYDVR0TAQH/BAIwADAf
          BgNVHSMEGDAWgBQJ/sAVkPmvZAqSErkmKGMMl+ynsjBwBggrBgEFBQcBAQRkMGIw
          LQYIKwYBBQUHMAKGIWh0dHA6Ly9jZXJ0cy5hcHBsZS5jb20vd3dkcmczLmRlcjAx
          BggrBgEFBQcwAYYlaHR0cDovL29jc3AuYXBwbGUuY29tL29jc3AwMy13d2RyZzMw
          MjCCAR4GA1UdIASCARUwggERMIIBDQYJKoZIhvdjZAUBMIH/MIHDBggrBgEFBQcC
          AjCBtgyBs1JlbGlhbmNlIG9uIHRoaXMgY2VydGlmaWNhdGUgYnkgYW55IHBhcnR5
          IGFzc3VtZXMgYWNjZXB0YW5jZSBvZiB0aGUgdGhlbiBhcHBsaWNhYmxlIHN0YW5k
          YXJkIHRlcm1zIGFuZCBjb25kaXRpb25zIG9mIHVzZSwgY2VydGlmaWNhdGUgcG9s
          aWN5IGFuZCBjZXJ0aWZpY2F0aW9uIHByYWN0aWNlIHN0YXRlbWVudHMuMDcGCCsG
          AQUFBwIBFitodHRwczovL3d3dy5hcHBsZS5jb20vY2VydGlmaWNhdGVhdXRob3Jp
          dHkvMBYGA1UdJQEB/wQMMAoGCCsGAQUFBwMDMB0GA1UdDgQWBBRw4w7ET6I41fJ+
          auajYadmDyx/uTAOBgNVHQ8BAf8EBAMCB4AwEwYKKoZIhvdjZAYBBAEB/wQCBQAw
          DQYJKoZIhvcNAQELBQADggEBAIj93GFwO8GzcyyvRScBJEFchqV7eFbF8n0RMnz5
          xnGkVKy2juL6FAMv2yczZcTU+6W8Fcc29ePzpCQ05zXRarvCEb/UjCsa1JQ/e/Ck
          rAvxp9akQ2rX8uqiylIBHh7qdcEx8mHYw1HbWqwwmlCXyaRsi0jJb9E6IWe3qgKo
          NFczUilA6wSQt8253btRgCS3N2cwcLo11EtERAgogD1UXz9Fyc0qgvBw3WsKz2p4
          qNN89B2EgRPwPxCta/zs9Doq33ZD2K3GtKTP7lHDtBQKEDdyKq5rsN/+FV3MVZzp
          kCEphzDPZcoxHxqrh56eeV7W2z5DWelH9AkVIU2CMKRxT5U=
          -----END CERTIFICATE-----
        APP_STORE_CONNECT_ISSUER_ID: 2e2875a6-4622-4c8d-af2c-288e1db44239
        APP_STORE_CONNECT_KEY_IDENTIFIER: Z2UZZ867U7
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"                
        BUNDLE_ID: "br.com.iabetsoficial" # <-- Put your bundle id here
        APP_STORE_ID: 1612458696 # <-- Use the TestFlight Apple id number (An automatically generated ID assigned to your app) found under General > App Information > Apple ID. 
      flutter: stable
    scripts:
      - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
        script: |
          keychain initialize
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files $BUNDLE_ID --type IOS_APP_STORE --create
      - name: Use system default keychain
        script: |
          keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          cd . && flutter packages pub get
      #- name: Flutter analyze
      #  script: |
      #    cd . && flutter analyze
      #- name: Flutter unit tests
      #  script: |
      #    cd . && flutter test
      #  ignore_failure: true          
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter build ipa and automatic versioning
        script: |
          flutter build ipa --release \
          --build-name=1.0.0 \
          --build-number=$(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_ID") + 1)) \
          --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      # See the following link for details about email publishing - https://docs.codemagic.io/yaml-publishing/email
      email:
        recipients:
          - marcosgomesneto@gmail.com
        notify:
          success: true # To receive a notification when a build succeeds
          failure: true # To not receive a notification when a build fails
      slack:
        # See the following link about how to connect your Slack account - https://docs.codemagic.io/yaml-publishing/slack
        channel: '#builds'
        notify_on_build_start: true # To receive a notification when a build starts
        notify:
          success: true # To receive a notification when a build succeeds
          failure: false # To not receive a notification when a build fails
      app_store_connect:   # https://docs.codemagic.io/publishing-yaml/distribution              
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER  # Alphanumeric value that identifies the API key, can also reference environment variable such as $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID # Alphanumeric value that identifies who created the API key, can also reference environment variable such as $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: false     