// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwaCNLWcqtZVaAfAU80VEolM5iec2-L_I',
    appId: '1:141556199031:web:7bc08019b89dee21b3e072',
    messagingSenderId: '141556199031',
    projectId: 'ia-bet',
    authDomain: 'ia-bet.firebaseapp.com',
    storageBucket: 'ia-bet.appspot.com',
    measurementId: 'G-6WHPX3H7F4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC69bBsRHOIkKqFYH6KIQcTgrxf4QCHNUk',
    appId: '1:141556199031:android:4e43418a495c6cf9b3e072',
    messagingSenderId: '141556199031',
    projectId: 'ia-bet',
    storageBucket: 'ia-bet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4Nkq6uVpKhV4209hTtZKX5s_BNOdR2hg',
    appId: '1:141556199031:ios:c4554ab44918e25db3e072',
    messagingSenderId: '141556199031',
    projectId: 'ia-bet',
    storageBucket: 'ia-bet.appspot.com',
    iosClientId: '141556199031-c2mqgcp9olm3o81m6bh9skg4rdc9nvon.apps.googleusercontent.com',
    iosBundleId: 'br.com.iabetsoficial',
  );
}
